// Ingredients.js
// you may have to change juice options to add ins
const sodaOptions = [
  { label: 'mtn. dew', value: 'mtn. dew', color: '#76cfae', emoji: '🏔️' },
  { label: 'diet mtn. dew', value: 'diet mtn. dew', color: '#a9dbc9', emoji: '🏔️' },
  { label: 'dr. pepper', value: 'dr. pepper', color: '#6A1B9A', emoji: '🩺' },
  { label: 'diet dr. pepper', value: 'diet dr. pepper', color: '#9C27B0', emoji: '🩺' },
  { label: 'dr. pepper zero', value: 'dr. pepper zero', color: '#9C27B9', emoji: '🩺' },
  { label: 'dr pepper cream soda', value: 'dr pepper cream soda', color: '#fc1947', emoji: '🩺' },
  { label: 'sprite', value: 'sprite', color: '#A2D2A6', emoji: '✨' },
  { label: 'sprite zero', value: 'sprite zero', color: '#C8E6C9', emoji: '✨' },
  { label: 'coke', value: 'coke', color: '#fc1947', emoji: '🥤' },
  { label: 'diet coke', value: 'diet coke', color: '#f75979', emoji: '🥤' },
  { label: 'coke zero', value: 'coke zero', color: '#fc1940', emoji: '🥤' },
  { label: 'pepsi', value: 'pepsi', color: '#1565C0', emoji: '🔵' },
  { label: 'diet pepsi', value: 'diet pepsi', color: '#1E88E5', emoji: '🔵' },
  { label: 'rootbeer', value: 'rootbeer', color: '#4E342E', emoji: '🍺' },
  { label: 'fanta', value: 'fanta', color: '#FF7043', emoji: '🍊' },
  { label: 'big red', value: 'big red', color: '#c75552', emoji: '❤️' },
  { label: 'poweraid', value: 'poweraid', color: '#71bde3', emoji: '⚡' },
  { label: 'lemonade', value: 'lemonade', color: '#FBC02D', emoji: '🍋' },
  { label: 'light lemonade', value: 'light lemonade', color: '#FFF176', emoji: '🍋' },
];

const syrupOptions = [
  { label: 'coconut', value: 'coconut', color: '#faf7f2', emoji: '🥥' },
  { label: 'passion fruit', value: 'passion fruit', color: '#FF7043', emoji: '🥭' },
  { label: 'mango', value: 'mango', color: '#FFB300', emoji: '🥭' },
  { label: 'guava', value: 'guava', color: '#fc86a5', emoji: '🍓' },
  { label: 'pineapple', value: 'pineapple', color: '#f5b12a', emoji: '🍍' },
  { label: 'banana', value: 'banana', color: '#FBC02D', emoji: '🍌' },
  { label: 'strawberry', value: 'strawberry', color: '#d91129', emoji: '🍓' },
  { label: 'raspberry', value: 'raspberry', color: '#b5093f', emoji: '🍓' },
  { label: 'blackberry', value: 'blackberry', color: '#4A148C', emoji: '🫐' },
  { label: 'pomegranate', value: 'pomegranate', color: '#b31537', emoji: '🍎' },
  { label: 'cranberry', value: 'cranberry', color: '#660143', emoji: '🍓' },
  { label: 'grape', value: 'grape', color: '#673AB7', emoji: '🍇' },
  { label: 'kiwi', value: 'kiwi', color: '#689e52', emoji: '🥝' },
  { label: 'huckleberry', value: 'huckleberry', color: '#3a0a70', emoji: '🫐' },
  { label: 'peach', value: 'peach', color: '#FF7043', emoji: '🍑' },
  { label: 'watermelon', value: 'watermelon', color: '#F44336', emoji: '🍉' },
  { label: 'green apple', value: 'green apple', color: '#8BC34A', emoji: '🍏' },
  { label: 'pear', value: 'pear', color: '#A5D6A7', emoji: '🍐' },
  { label: 'cherry', value: 'cherry', color: '#D32F2F', emoji: '🍒' },
  { label: 'orange', value: 'orange', color: '#FF9800', emoji: '🍊' },
  { label: 'blood orange', value: 'blood orange', color: '#F57C00', emoji: '🍊' },
  { label: 'grapefruit', value: 'grapefruit', color: '#FF4081', emoji: '🍊' },
  { label: 'sweetened lime', value: 'sweetened lime', color: '#8BC34A', emoji: '🍋' },
  { label: 'lemon', value: 'lemon', color: '#FFEB3B', emoji: '🍋' },
  { label: 'lime', value: 'lime', color: '#CDDC39', emoji: '🍋' },
  { label: 'vanilla', value: 'vanilla', color: '#ffeccf', emoji: '🌼' },
  { label: 'cupcake', value: 'cupcake', color: '#FF4081', emoji: '🧁' },
  { label: 'salted caramel', value: 'salted caramel', color: '#6D4C41', emoji: '🍫' },
  { label: 'chocolate milano', value: 'chocolate milano', color: '#3E2723', emoji: '🍫' },
  { label: 'cinnamon', value: 'cinnamon', color: '#795548', emoji: '🤎' },
  { label: 'choc chip cookie dough', value: 'choc chip cookie dough', color: '#D7CCC8', emoji: '🍪' },
  { label: 'brown sugar cinnamon', value: 'brown sugar cinnamon', color: '#6D4C41', emoji: '🍪' },
  { label: 'hazelnut', value: 'hazelnut', color: '#5D4037', emoji: '🌰' },
  { label: 'white chocolate', value: 'white chocolate', color: '#F5F5F5', emoji: '🍫' },
  { label: 'butterscotch', value: 'butterscotch', color: '#FFB74D', emoji: '🍯' },
  { label: 'blue raspberry', value: 'blue raspberry', color: '#2196F3', emoji: '💙' },
  { label: 'sour', value: 'sour', color: '#CDDC39', emoji: '😖' },
  { label: 'blue curacao', value: 'blue curacao', color: '#1E88E5', emoji: '💙' },
  { label: 'bubble gum', value: 'bubble gum', color: '#fc49b5', emoji: '🍬' },
  { label: 'cotton candy', value: 'cotton candy', color: '#b9f8fa', emoji: '🌈' },
  { label: 'mojito', value: 'mojito', color: '#8cc740', emoji: '🌿' },
  { label: 'cucumber', value: 'cucumber', color: '#35751b', emoji: '🥒' },
  { label: 'lavender', value: 'lavender', color: '#d894f7', emoji: '🌸' },
  { label: 'pumpkin spice', value: 'pumpkin spice', color: '#db7d3d', emoji: '🎃' },
  { label: 'peppermint', value: 'peppermint', color: '#fc5372', emoji: '🌿' },
  { label: 'irish cream', value: 'irish cream', color: '#e1f7dc', emoji: '🍀' },
  { label: 'gingerbread', value: 'gingerbread', color: '#804619', emoji: '🍪' },
  { label: 'butterbrew mix', value: 'butterbrew mix', color: '#ad632a', emoji: '🍯' },

];
const AddInOptions = [
  { label: 'cream', value: 'cream', color: '#ffdba6', emoji: '🥛' },
  { label: 'coconot cream', value: 'coconot cream', color: '#ffdba0', emoji: '🥥' },
  { label: 'whip', value: 'whip', color: '#ffdbaf', emoji: '🍦' },
  { label: 'lime wedge', value: 'lime wedge', color: '#d3fc3f', emoji: '🍈' },
  { label: 'lemon wedge', value: 'lemon wedge', color: '#fae170', emoji: '🍋' },
  { label: 'french vanilla creamer', value: 'french vanilla creamer', color: '#deb695', emoji: '🌼' },
  { label: 'candy', value: 'candy', color: '#FF9800', emoji: '🍬' },
  { label: 'sprinkles', value: 'sprinkles', color: '#FF4081', emoji: '🌈' },
  { label: 'strawberry puree', value: 'strawberry puree', color: '#E91E63', emoji: '🍓' },
  { label: 'peach puree', value: 'peach puree', color: '#FF7043', emoji: '🍑' },
  { label: 'mango puree', value: 'mango puree', color: '#faab23', emoji: '🥭' },
  { label: 'raspberry puree', value: 'raspberry puree', color: '#D50000', emoji: '🫐' },
];

export { sodaOptions, syrupOptions, AddInOptions };
