// Ingredient color and emoji metadata, keyed by lowercase name
// Used for visual previews (Gif colors, labels) and admin dropdowns
const ingredientMeta = {
  // Sodas
  'mtn. dew': { color: '#76cfae', emoji: '🏔️' },
  'diet mtn. dew': { color: '#a9dbc9', emoji: '🏔️' },
  'dr. pepper': { color: '#6A1B9A', emoji: '🩺' },
  'diet dr. pepper': { color: '#9C27B0', emoji: '🩺' },
  'dr. pepper zero': { color: '#9C27B9', emoji: '🩺' },
  'dr pepper cream soda': { color: '#fc1947', emoji: '🩺' },
  'sprite': { color: '#A2D2A6', emoji: '✨' },
  'sprite zero': { color: '#C8E6C9', emoji: '✨' },
  'coke': { color: '#fc1947', emoji: '🥤' },
  'diet coke': { color: '#f75979', emoji: '🥤' },
  'coke zero': { color: '#fc1940', emoji: '🥤' },
  'pepsi': { color: '#1565C0', emoji: '🔵' },
  'diet pepsi': { color: '#1E88E5', emoji: '🔵' },
  'rootbeer': { color: '#4E342E', emoji: '🍺' },
  'fanta': { color: '#FF7043', emoji: '🍊' },
  'big red': { color: '#c75552', emoji: '❤️' },
  'powerade': { color: '#71bde3', emoji: '⚡' },
  'lemonade': { color: '#FBC02D', emoji: '🍋' },
  'light lemonade': { color: '#FFF176', emoji: '🍋' },

  // Syrups
  'coconut': { color: '#faf7f2', emoji: '🥥' },
  'passion fruit': { color: '#FF7043', emoji: '🥭' },
  'mango': { color: '#FFB300', emoji: '🥭' },
  'guava': { color: '#fc86a5', emoji: '🍓' },
  'pineapple': { color: '#f5b12a', emoji: '🍍' },
  'banana': { color: '#FBC02D', emoji: '🍌' },
  'strawberry': { color: '#d91129', emoji: '🍓' },
  'raspberry': { color: '#b5093f', emoji: '🍓' },
  'blackberry': { color: '#4A148C', emoji: '🫐' },
  'pomegranate': { color: '#b31537', emoji: '🍎' },
  'cranberry': { color: '#660143', emoji: '🍓' },
  'grape': { color: '#673AB7', emoji: '🍇' },
  'kiwi': { color: '#689e52', emoji: '🥝' },
  'huckleberry': { color: '#3a0a70', emoji: '🫐' },
  'peach': { color: '#FF7043', emoji: '🍑' },
  'watermelon': { color: '#F44336', emoji: '🍉' },
  'green apple': { color: '#8BC34A', emoji: '🍏' },
  'pear': { color: '#A5D6A7', emoji: '🍐' },
  'cherry': { color: '#D32F2F', emoji: '🍒' },
  'orange': { color: '#FF9800', emoji: '🍊' },
  'blood orange': { color: '#F57C00', emoji: '🍊' },
  'grapefruit': { color: '#FF4081', emoji: '🍊' },
  'sweetened lime': { color: '#8BC34A', emoji: '🍋' },
  'lemon': { color: '#FFEB3B', emoji: '🍋' },
  'lime': { color: '#CDDC39', emoji: '🍋' },
  'lemon lime': { color: '#CDDC39', emoji: '🍋' },
  'vanilla': { color: '#ffeccf', emoji: '🌼' },
  'cupcake': { color: '#FF4081', emoji: '🧁' },
  'salted caramel': { color: '#6D4C41', emoji: '🍫' },
  'chocolate': { color: '#3E2723', emoji: '🍫' },
  'chocolate milano': { color: '#3E2723', emoji: '🍫' },
  'milano': { color: '#3E2723', emoji: '🍫' },
  'cinnamon': { color: '#795548', emoji: '🤎' },
  'choc chip cookie dough': { color: '#D7CCC8', emoji: '🍪' },
  'brown sugar cinnamon': { color: '#6D4C41', emoji: '🍪' },
  'hazelnut': { color: '#5D4037', emoji: '🌰' },
  'white chocolate': { color: '#F5F5F5', emoji: '🍫' },
  'butterscotch': { color: '#FFB74D', emoji: '🍯' },
  'blue raspberry': { color: '#2196F3', emoji: '💙' },
  'sour': { color: '#CDDC39', emoji: '😖' },
  'blue curacao': { color: '#1E88E5', emoji: '💙' },
  'bubble gum': { color: '#fc49b5', emoji: '🍬' },
  'cotton candy': { color: '#b9f8fa', emoji: '🌈' },
  'mojito': { color: '#8cc740', emoji: '🌿' },
  'cucumber': { color: '#35751b', emoji: '🥒' },
  'lavender': { color: '#d894f7', emoji: '🌸' },
  'pumpkin spice': { color: '#db7d3d', emoji: '🎃' },
  'peppermint': { color: '#fc5372', emoji: '🌿' },
  'irish cream': { color: '#e1f7dc', emoji: '🍀' },
  'gingerbread': { color: '#804619', emoji: '🍪' },
  'butterbrew mix': { color: '#ad632a', emoji: '🍯' },

  // Add-Ins
  'cream': { color: '#ffdba6', emoji: '🥛' },
  'coconut cream': { color: '#ffdba0', emoji: '🥥' },
  'whip': { color: '#ffdbaf', emoji: '🍦' },
  'lime wedge': { color: '#d3fc3f', emoji: '🍈' },
  'lemon wedge': { color: '#fae170', emoji: '🍋' },
  'french vanilla creamer': { color: '#deb695', emoji: '🌼' },
  'candy sprinkles': { color: '#FF9800', emoji: '🍬' },
  'candy': { color: '#FF9800', emoji: '🍬' },
  'sprinkles': { color: '#FF4081', emoji: '🌈' },
  'strawberry puree': { color: '#E91E63', emoji: '🍓' },
  'peach puree': { color: '#FF7043', emoji: '🍑' },
  'mango puree': { color: '#faab23', emoji: '🥭' },
  'raspberry puree': { color: '#D50000', emoji: '🫐' },
};

export default ingredientMeta;
