# Generated by Django 5.1.15 on 2026-02-01 22:24

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemType', models.CharField(choices=[('Soda', 'Soda'), ('Syrup', 'Syrup'), ('Add In', 'Add In'), ('Physical', 'Physical')], max_length=50)),
                ('Quantity', models.PositiveIntegerField()),
                ('ThresholdLevel', models.PositiveIntegerField()),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('RevenueID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField(default=1)),
                ('TotalAmount', models.FloatField(default=0.0)),
                ('SaleDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Refunded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('DrinkID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('SyrupsUsed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('SodaUsed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('AddIns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Price', models.FloatField()),
                ('Size', models.CharField(default='m')),
                ('Ice', models.CharField(default='normal')),
                ('User_Created', models.BooleanField()),
                ('Favorite', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=500)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Type', models.CharField(max_length=50)),
                ('Global', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('PaymentStatus', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('remade', 'Remade')], default='pending', max_length=50)),
                ('PickupTime', models.DateTimeField(blank=True, null=True)),
                ('CreationTime', models.DateTimeField(auto_now_add=True)),
                ('LockerCombo', models.BigIntegerField(null=True)),
                ('StripeID', models.CharField()),
                ('Drinks', models.ManyToManyField(to='backend.drink')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('PreferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('Preference', models.CharField(max_length=100)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
