# Generated by Django 5.1.2 on 2026-03-09 22:15

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_update', 'Status Update'), ('supply_request', 'Supply Request'), ('heartbeat', 'Heartbeat'), ('user_sync', 'User Sync')], max_length=50)),
                ('payload', models.JSONField()),
                ('target_node', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HubRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.IntegerField(unique=True)),
                ('hub_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('is_master', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hub Registries',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('ItemType', models.CharField(choices=[('Soda', 'Soda'), ('Syrup', 'Syrup'), ('Add In', 'Add In'), ('Physical', 'Physical')], max_length=50)),
                ('Quantity', models.PositiveIntegerField()),
                ('ThresholdLevel', models.PositiveIntegerField()),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100, unique=True)),
                ('store_id', models.IntegerField()),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('OUT_OF_ORDER', 'Out of Order'), ('SCHEDULE_SERVICE', 'Schedule Service'), ('REPAIR_START', 'Repair Start'), ('REPAIR_END', 'Repair End')], default='NORMAL', max_length=30)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('repair_notes', models.TextField(blank=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('node_type', models.CharField(choices=[('store', 'Store'), ('hub', 'Hub'), ('master', 'Master Hub')], max_length=20)),
                ('shared_secret', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hub_api_endpoint', models.URLField(blank=True)),
                ('is_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('RevenueID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField(default=1)),
                ('TotalAmount', models.FloatField(default=0.0)),
                ('SaleDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Refunded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(unique=True)),
                ('store_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('api_endpoint', models.URLField()),
                ('public_key', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Store Registries',
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('Soda', 'Soda'), ('Syrup', 'Syrup'), ('Add In', 'Add In'), ('Physical', 'Physical')], max_length=50)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('user_pull', 'User Pull'), ('catalog_push', 'Catalog Push'), ('status_update', 'Status Update')], max_length=50)),
                ('source_store_id', models.IntegerField()),
                ('target_store_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('user_data', models.JSONField()),
                ('source_store_id', models.IntegerField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'User Caches',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('DrinkID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('SyrupsUsed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('SodaUsed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('AddIns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Price', models.FloatField()),
                ('Size', models.CharField(default='m')),
                ('Ice', models.CharField(default='normal')),
                ('User_Created', models.BooleanField()),
                ('Favorite', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=500)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Type', models.CharField(max_length=50)),
                ('Global', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('PaymentStatus', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('remade', 'Remade')], default='pending', max_length=50)),
                ('PickupTime', models.DateTimeField(blank=True, null=True)),
                ('CreationTime', models.DateTimeField(auto_now_add=True)),
                ('LockerCombo', models.BigIntegerField(null=True)),
                ('StripeID', models.CharField()),
                ('Drinks', models.ManyToManyField(to='backend.drink')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('PreferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('Preference', models.CharField(max_length=100)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_profile', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region')),
            ],
            options={
                'verbose_name_plural': 'Logistics Manager Profiles',
            },
        ),
        migrations.CreateModel(
            name='RepairStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('assigned_store_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repair Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('inventory_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region')),
            ],
            options={
                'verbose_name_plural': 'Supply Hubs',
            },
        ),
    ]
