# Generated by Django 5.1.2 on 2026-03-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_seed_test_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='store_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
