# Generated by Django 5.1.2 on 2026-03-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_machine_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeregistry',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='backend.region'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='backend.region'),
        ),
    ]
