# Generated by Django 5.1.2 on 2026-03-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_storeregistry_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeregistry',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storeregistry',
            name='machine_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeregistry',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to='backend.managerprofile'),
        ),
        migrations.CreateModel(
            name='SupplyHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventory_pct', models.FloatField(default=0.0)),
                ('active_deliveries_count', models.IntegerField(default=0)),
                ('pending_orders_count', models.IntegerField(default=0)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_hubs', to='backend.region')),
            ],
        ),
    ]
