# Generated by Django 5.1.2 on 2026-03-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_supply_hub_and_store_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('syrup', 'Syrup'), ('soda', 'Soda'), ('add-in', 'Add-In'), ('physical', 'Physical')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='backend.supplyhub')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('syrup', 'Syrup'), ('soda', 'Soda'), ('add-in', 'Add-In'), ('physical', 'Physical')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('days_remaining', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='backend.storeregistry')),
            ],
        ),
    ]
