# Generated by Django 5.1.2 on 2026-03-31 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_hubinventoryitem_storeinventoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyrequest',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='region',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='store_id',
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_requests', to='backend.supplyhub'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='backend.storeregistry'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
    ]
