# Generated by Django 5.1.2 on 2026-04-04 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_visitingusercache_favorite_drinks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='store',
        ),
        migrations.AlterField(
            model_name='seasonaldrink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='week', max_length=10)),
                ('days', models.JSONField(default=dict)),
                ('end_type', models.CharField(choices=[('never', 'Never'), ('on', 'On Date'), ('after', 'After N')], default='never', max_length=10)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drinks', models.ManyToManyField(to='backend.drink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
