# Generated by Django 5.1.2 on 2026-04-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_userprofile_store_alter_seasonaldrink_id_and_more'),
        ('backend', '0015_seed_catalog'),
    ]

    operations = [
    ]
