services:
  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:8-alpine
    restart: always

  celery:
    build: .
    command: sh -c "python manage.py migrate --noinput && celery -A codepop_backend worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    restart: always

  celery-beat:
    build: .
    command: sh -c "python manage.py migrate --noinput && celery -A codepop_backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    restart: always

volumes:
  postgres_data:
  huggingface_cache: