"""
Django settings for codepop_backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from dotenv import load_dotenv
load_dotenv()

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY must be set in environment variables (.env file)")

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'TODO: get a new secret stripe key')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'TODO: get a new publishable stripe key')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django_celery_beat',
    'backend'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'backend.middleware.NodeIdentityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codepop_backend.urls'

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codepop_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'codepop'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# ---------------------------------------------------------------------------
# Node identity (hub mesh + regional stores; no master hub)
# ---------------------------------------------------------------------------
try:
    STORE_ID = int(os.getenv('STORE_ID', '0'))
except ValueError:
    raise ImproperlyConfigured("STORE_ID must be a valid integer")
STORE_NAME = os.getenv('STORE_NAME', f'Store {STORE_ID}')
REGION = os.getenv('REGION', 'logan')
API_ENDPOINT = os.getenv('API_ENDPOINT', '')
LATITUDE = float(os.getenv('LATITUDE', '0.0'))
LONGITUDE = float(os.getenv('LONGITUDE', '0.0'))

# Node role: 'hub' (regional coordinator) or 'store' (customer-facing node)
NODE_ROLE = (os.getenv('NODE_ROLE', 'store') or 'store').strip().lower()
if NODE_ROLE not in ('hub', 'store'):
    raise ImproperlyConfigured("NODE_ROLE must be 'hub' or 'store'")

# Stores: URL of this node's regional hub. Hubs: leave empty.
UPSTREAM_HUB_URL = (os.getenv('UPSTREAM_HUB_URL', '') or os.getenv('HUB_URL', '')).strip()
HUB_URL = UPSTREAM_HUB_URL

# Derived: True if this node is a hub (no master hub concept)
IS_HUB = NODE_ROLE == 'hub'

# Hubs only: comma-separated list of other hub base URLs for hub-to-hub mesh
PEER_HUB_URLS = [
    url.strip()
    for url in os.getenv('PEER_HUB_URLS', '').split(',')
    if url.strip()
]

# Inter-node authentication (dev fallback; prefer per-node NodeCertificate in prod)
INTER_NODE_SECRET = os.getenv('INTER_NODE_SECRET', '')

# Distributed mode: this node participates in the network (hub or store with upstream)
_participates = IS_HUB or bool(UPSTREAM_HUB_URL) or bool(PEER_HUB_URLS)
if _participates and not INTER_NODE_SECRET:
    raise ImproperlyConfigured(
        "INTER_NODE_SECRET must be set in .env for distributed deployments. "
        "Required for inter-node communication. Set INTER_NODE_SECRET in your .env file."
    )
if _participates:
    if str(STORE_ID).strip() == '':
        raise ImproperlyConfigured("STORE_ID must be set for hub or store nodes in distributed mode")
    if not REGION:
        raise ImproperlyConfigured("REGION must be set for hub or store nodes in distributed mode")
    if not API_ENDPOINT:
        raise ImproperlyConfigured("API_ENDPOINT must be set for hub or store nodes in distributed mode")

# Celery
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://redis:6379/0')


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================

# Celery broker: Redis (same instance used for caching)
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://redis:6379/0')

# Celery task settings
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'

# Celery Beat: Periodic tasks
# NOTE: register_with_hub is NOT on a beat schedule. It's triggered once on app startup
# via apps.py BackendConfig.ready() with exponential backoff until the hub is reachable.
CELERY_BEAT_SCHEDULE = {
    'heartbeat-every-30-seconds': {
        'task': 'backend.tasks.heartbeat_task',
        'schedule': 30.0,  # every 30 seconds
    },
    'process-event-queue-every-10-seconds': {
        'task': 'backend.tasks.process_event_queue',
        'schedule': 10.0,  # every 10 seconds
    },
    'check-dead-stores-every-2-minutes': {
        'task': 'backend.tasks.check_dead_stores',
        'schedule': 120.0,  # every 2 minutes
    },
}
