export const LOGISTICS_MANAGER = {
  id: 'LM-001',
  firstName: 'Sarah',
  lastName: 'Chen',
  hub: 'Chicago Hub',
  region: 'Midwest Region',
};

export const STORES = [
  {
    id: 'S-001',
    name: 'Chicago Downtown',
    address: '100 N Michigan Ave, Chicago, IL 60601',
    region: 'Midwest Region',
    supplyHealthStatus: 'critical',
    daysRemaining: 0,
    restockByDate: '2026-03-28',
    activeRequests: 2,
    ingredientLevels: [
      { category: 'Syrups', pct: 8 },
      { category: 'Sodas', pct: 5 },
      { category: 'Add-ins', pct: 12 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 45 },
      { date: 'Mar 27', level: 32 },
      { date: 'Mar 28', level: 15 },
      { date: 'Mar 29', level: 8 },
      { date: 'Mar 30', level: 5 },
    ],
    requests: [
      { id: 'REQ-2026-001', summary: 'Emergency cherry syrup', submittedDate: '2026-03-27', status: 'pending', eta: '2026-03-28' },
      { id: 'REQ-2026-002', summary: 'Soda assortment restock', submittedDate: '2026-03-26', status: 'approved', eta: '2026-03-29' },
    ],
    history: [
      { date: '2026-03-20', ingredients: 'Cherry syrup, Lime soda', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
      { date: '2026-03-13', ingredients: 'Cherry syrup, Mango syrup, Vanilla soda', qty: '3 cases', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
    ],
  },
  {
    id: 'S-002',
    name: 'Chicago North Shore',
    address: '4200 N Clark St, Chicago, IL 60613',
    region: 'Midwest Region',
    supplyHealthStatus: 'critical',
    daysRemaining: 1,
    restockByDate: '2026-03-29',
    activeRequests: 1,
    ingredientLevels: [
      { category: 'Syrups', pct: 18 },
      { category: 'Sodas', pct: 22 },
      { category: 'Add-ins', pct: 15 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 55 },
      { date: 'Mar 27', level: 42 },
      { date: 'Mar 28', level: 28 },
      { date: 'Mar 29', level: 18 },
      { date: 'Mar 30', level: 8 },
    ],
    requests: [
      { id: 'REQ-2026-003', summary: 'Vanilla syrup emergency', submittedDate: '2026-03-27', status: 'pending', eta: '2026-03-28' },
    ],
    history: [
      { date: '2026-03-20', ingredients: 'Cherry syrup', qty: '1 case', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
    ],
  },
  {
    id: 'S-003',
    name: 'Chicago West Loop',
    address: '800 W Randolph St, Chicago, IL 60661',
    region: 'Midwest Region',
    supplyHealthStatus: 'low',
    daysRemaining: 2,
    restockByDate: '2026-03-30',
    activeRequests: 1,
    ingredientLevels: [
      { category: 'Syrups', pct: 35 },
      { category: 'Sodas', pct: 38 },
      { category: 'Add-ins', pct: 32 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 65 },
      { date: 'Mar 27', level: 52 },
      { date: 'Mar 28', level: 42 },
      { date: 'Mar 29', level: 32 },
      { date: 'Mar 30', level: 22 },
    ],
    requests: [
      { id: 'REQ-2026-004', summary: 'Weekly ingredient request', submittedDate: '2026-03-26', status: 'in_transit', eta: '2026-03-29' },
    ],
    history: [
      { date: '2026-03-20', ingredients: 'Assorted syrups and sodas', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
    ],
  },
  {
    id: 'S-004',
    name: 'Chicago South Loop',
    address: '1400 S Michigan Ave, Chicago, IL 60605',
    region: 'Midwest Region',
    supplyHealthStatus: 'low',
    daysRemaining: 3,
    restockByDate: '2026-03-31',
    activeRequests: 0,
    ingredientLevels: [
      { category: 'Syrups', pct: 48 },
      { category: 'Sodas', pct: 52 },
      { category: 'Add-ins', pct: 45 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 72 },
      { date: 'Mar 27', level: 62 },
      { date: 'Mar 28', level: 52 },
      { date: 'Mar 29', level: 42 },
      { date: 'Mar 30', level: 35 },
    ],
    requests: [],
    history: [
      { date: '2026-03-20', ingredients: 'Standard weekly pack', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
    ],
  },
  {
    id: 'S-005',
    name: 'Chicago Lincoln Park',
    address: '2400 N Lincoln Ave, Chicago, IL 60614',
    region: 'Midwest Region',
    supplyHealthStatus: 'good',
    daysRemaining: 5,
    restockByDate: '2026-04-02',
    activeRequests: 0,
    ingredientLevels: [
      { category: 'Syrups', pct: 68 },
      { category: 'Sodas', pct: 72 },
      { category: 'Add-ins', pct: 65 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 82 },
      { date: 'Mar 27', level: 75 },
      { date: 'Mar 28', level: 68 },
      { date: 'Mar 29', level: 62 },
      { date: 'Mar 30', level: 55 },
    ],
    requests: [],
    history: [
      { date: '2026-03-20', ingredients: 'Assorted syrups', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
    ],
  },
  {
    id: 'S-006',
    name: 'Chicago Bucktown',
    address: '1900 W Division St, Chicago, IL 60622',
    region: 'Midwest Region',
    supplyHealthStatus: 'good',
    daysRemaining: 6,
    restockByDate: '2026-04-03',
    activeRequests: 0,
    ingredientLevels: [
      { category: 'Syrups', pct: 75 },
      { category: 'Sodas', pct: 78 },
      { category: 'Add-ins', pct: 72 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 85 },
      { date: 'Mar 27', level: 80 },
      { date: 'Mar 28', level: 75 },
      { date: 'Mar 29', level: 70 },
      { date: 'Mar 30', level: 65 },
    ],
    requests: [],
    history: [
      { date: '2026-03-20', ingredients: 'Assorted ingredients', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Regular weekly delivery' },
    ],
  },
  {
    id: 'S-007',
    name: 'Milwaukee Downtown',
    address: '600 N Water St, Milwaukee, WI 53202',
    region: 'Midwest Region',
    supplyHealthStatus: 'critical',
    daysRemaining: 0,
    restockByDate: '2026-03-28',
    activeRequests: 2,
    ingredientLevels: [
      { category: 'Syrups', pct: 6 },
      { category: 'Sodas', pct: 10 },
      { category: 'Add-ins', pct: 8 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 38 },
      { date: 'Mar 27', level: 25 },
      { date: 'Mar 28', level: 12 },
      { date: 'Mar 29', level: 6 },
      { date: 'Mar 30', level: 2 },
    ],
    requests: [
      { id: 'REQ-2026-005', summary: 'Emergency restock', submittedDate: '2026-03-27', status: 'pending', eta: '2026-03-28' },
      { id: 'REQ-2026-006', summary: 'Soda restocking', submittedDate: '2026-03-27', status: 'pending', eta: '2026-03-28' },
    ],
    history: [
      { date: '2026-03-20', ingredients: 'Weekly assortment', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Cross-hub delivery' },
    ],
  },
  {
    id: 'S-008',
    name: 'Milwaukee Bay View',
    address: '2428 S Bay St, Milwaukee, WI 53207',
    region: 'Midwest Region',
    supplyHealthStatus: 'low',
    daysRemaining: 2,
    restockByDate: '2026-03-30',
    activeRequests: 1,
    ingredientLevels: [
      { category: 'Syrups', pct: 32 },
      { category: 'Sodas', pct: 35 },
      { category: 'Add-ins', pct: 30 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 60 },
      { date: 'Mar 27', level: 48 },
      { date: 'Mar 28', level: 38 },
      { date: 'Mar 29', level: 28 },
      { date: 'Mar 30', level: 18 },
    ],
    requests: [
      { id: 'REQ-2026-007', summary: 'Ingredient restocking', submittedDate: '2026-03-26', status: 'in_transit', eta: '2026-03-29' },
    ],
    history: [
      { date: '2026-03-20', ingredients: 'Standard pack', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Cross-hub delivery' },
    ],
  },
  {
    id: 'S-009',
    name: 'Madison Central',
    address: '7 W Main St, Madison, WI 53703',
    region: 'Midwest Region',
    supplyHealthStatus: 'good',
    daysRemaining: 4,
    restockByDate: '2026-04-01',
    activeRequests: 0,
    ingredientLevels: [
      { category: 'Syrups', pct: 58 },
      { category: 'Sodas', pct: 62 },
      { category: 'Add-ins', pct: 55 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 75 },
      { date: 'Mar 27', level: 68 },
      { date: 'Mar 28', level: 62 },
      { date: 'Mar 29', level: 56 },
      { date: 'Mar 30', level: 50 },
    ],
    requests: [],
    history: [
      { date: '2026-03-20', ingredients: 'Weekly assortment', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Cross-hub delivery' },
    ],
  },
  {
    id: 'S-010',
    name: 'Des Moines Capital',
    address: '801 Grand Ave, Des Moines, IA 50309',
    region: 'Midwest Region',
    supplyHealthStatus: 'good',
    daysRemaining: 7,
    restockByDate: '2026-04-04',
    activeRequests: 0,
    ingredientLevels: [
      { category: 'Syrups', pct: 82 },
      { category: 'Sodas', pct: 85 },
      { category: 'Add-ins', pct: 80 },
    ],
    forecastData: [
      { date: 'Mar 26', level: 92 },
      { date: 'Mar 27', level: 88 },
      { date: 'Mar 28', level: 82 },
      { date: 'Mar 29', level: 78 },
      { date: 'Mar 30', level: 72 },
    ],
    requests: [],
    history: [
      { date: '2026-03-20', ingredients: 'Standard pack', qty: '2 cases', fromLocation: 'Chicago Hub', notes: 'Cross-hub delivery' },
    ],
  },
];

export const INVENTORY_ITEMS = [
  {
    id: 'INV-001',
    name: 'Cherry Syrup',
    category: 'Syrups',
    currentLevelPct: 32,
    avgDailyUsage: 4.2,
    daysRemaining: 7,
    trendDirection: 'down',
    trendPct: -12,
    status: 'low',
  },
  {
    id: 'INV-002',
    name: 'Mango Syrup',
    category: 'Syrups',
    currentLevelPct: 58,
    avgDailyUsage: 3.5,
    daysRemaining: 16,
    trendDirection: 'down',
    trendPct: -5,
    status: 'in_stock',
  },
  {
    id: 'INV-003',
    name: 'Vanilla Syrup',
    category: 'Syrups',
    currentLevelPct: 72,
    avgDailyUsage: 2.8,
    daysRemaining: 25,
    trendDirection: 'up',
    trendPct: 8,
    status: 'in_stock',
  },
  {
    id: 'INV-004',
    name: 'Lime Syrup',
    category: 'Syrups',
    currentLevelPct: 45,
    avgDailyUsage: 3.2,
    daysRemaining: 14,
    trendDirection: 'flat',
    trendPct: 0,
    status: 'in_stock',
  },
  {
    id: 'INV-005',
    name: 'Cola Syrup',
    category: 'Syrups',
    currentLevelPct: 15,
    avgDailyUsage: 5.1,
    daysRemaining: 3,
    trendDirection: 'down',
    trendPct: -18,
    status: 'critical',
  },
  {
    id: 'INV-006',
    name: 'Cherry Soda',
    category: 'Sodas',
    currentLevelPct: 25,
    avgDailyUsage: 6.5,
    daysRemaining: 3,
    trendDirection: 'down',
    trendPct: -15,
    status: 'critical',
  },
  {
    id: 'INV-007',
    name: 'Lime Soda',
    category: 'Sodas',
    currentLevelPct: 52,
    avgDailyUsage: 4.2,
    daysRemaining: 12,
    trendDirection: 'down',
    trendPct: -8,
    status: 'in_stock',
  },
  {
    id: 'INV-008',
    name: 'Vanilla Soda',
    category: 'Sodas',
    currentLevelPct: 68,
    avgDailyUsage: 3.8,
    daysRemaining: 17,
    trendDirection: 'flat',
    trendPct: 2,
    status: 'in_stock',
  },
  {
    id: 'INV-009',
    name: 'Mango Soda',
    category: 'Sodas',
    currentLevelPct: 38,
    avgDailyUsage: 5.0,
    daysRemaining: 7,
    trendDirection: 'down',
    trendPct: -12,
    status: 'low',
  },
  {
    id: 'INV-010',
    name: 'Cola Soda',
    category: 'Sodas',
    currentLevelPct: 18,
    avgDailyUsage: 7.2,
    daysRemaining: 2,
    trendDirection: 'down',
    trendPct: -22,
    status: 'critical',
  },
  {
    id: 'INV-011',
    name: 'Whipped Cream',
    category: 'Add-ins',
    currentLevelPct: 55,
    avgDailyUsage: 2.1,
    daysRemaining: 26,
    trendDirection: 'flat',
    trendPct: -2,
    status: 'in_stock',
  },
  {
    id: 'INV-012',
    name: 'Gummy Bears',
    category: 'Add-ins',
    currentLevelPct: 42,
    avgDailyUsage: 3.0,
    daysRemaining: 14,
    trendDirection: 'down',
    trendPct: -6,
    status: 'in_stock',
  },
  {
    id: 'INV-013',
    name: 'Chocolate Sprinkles',
    category: 'Add-ins',
    currentLevelPct: 35,
    avgDailyUsage: 2.8,
    daysRemaining: 12,
    trendDirection: 'down',
    trendPct: -10,
    status: 'low',
  },
  {
    id: 'INV-014',
    name: 'Rainbow Sprinkles',
    category: 'Add-ins',
    currentLevelPct: 62,
    avgDailyUsage: 2.5,
    daysRemaining: 24,
    trendDirection: 'up',
    trendPct: 5,
    status: 'in_stock',
  },
  {
    id: 'INV-015',
    name: 'Nuts Mix',
    category: 'Add-ins',
    currentLevelPct: 48,
    avgDailyUsage: 1.5,
    daysRemaining: 32,
    trendDirection: 'flat',
    trendPct: 1,
    status: 'in_stock',
  },
  {
    id: 'INV-016',
    name: 'Caramel Sauce',
    category: 'Add-ins',
    currentLevelPct: 28,
    avgDailyUsage: 3.5,
    daysRemaining: 8,
    trendDirection: 'down',
    trendPct: -14,
    status: 'low',
  },
  {
    id: 'INV-017',
    name: 'Chocolate Sauce',
    category: 'Add-ins',
    currentLevelPct: 12,
    avgDailyUsage: 4.2,
    daysRemaining: 2,
    trendDirection: 'down',
    trendPct: -20,
    status: 'critical',
  },
];

export const DELIVERIES = [
  {
    id: 'D-001',
    storeName: 'Chicago Downtown',
    storeAddress: '100 N Michigan Ave, Chicago, IL',
    eta: '2026-03-28T10:30',
    driver: 'Mike Johnson',
    status: 'in_transit',
    currentSupplyPct: 8,
    forecastedDepletionDate: '2026-03-28',
    suggestedRestockWindow: 'immediate',
    lastDelivery: '2026-03-20',
  },
  {
    id: 'D-002',
    storeName: 'Milwaukee Downtown',
    storeAddress: '600 N Water St, Milwaukee, WI',
    eta: '2026-03-28T14:00',
    driver: 'Sarah Martinez',
    status: 'out_for_delivery',
    currentSupplyPct: 10,
    forecastedDepletionDate: '2026-03-28',
    suggestedRestockWindow: 'immediate',
    lastDelivery: '2026-03-20',
  },
  {
    id: 'D-003',
    storeName: 'Chicago North Shore',
    storeAddress: '4200 N Clark St, Chicago, IL',
    eta: '2026-03-29T09:00',
    driver: 'James Rodriguez',
    status: 'in_transit',
    currentSupplyPct: 22,
    forecastedDepletionDate: '2026-03-29',
    suggestedRestockWindow: 'this_week',
    lastDelivery: '2026-03-20',
  },
  {
    id: 'D-004',
    storeName: 'Chicago West Loop',
    storeAddress: '800 W Randolph St, Chicago, IL',
    eta: '2026-03-29T11:30',
    driver: 'Robert Chen',
    status: 'in_transit',
    currentSupplyPct: 38,
    forecastedDepletionDate: '2026-03-30',
    suggestedRestockWindow: 'this_week',
    lastDelivery: '2026-03-20',
  },
  {
    id: 'D-005',
    storeName: 'Milwaukee Bay View',
    storeAddress: '2428 S Bay St, Milwaukee, WI',
    eta: '2026-03-29T13:15',
    driver: 'Lisa Anderson',
    status: 'in_transit',
    currentSupplyPct: 35,
    forecastedDepletionDate: '2026-03-30',
    suggestedRestockWindow: 'this_week',
    lastDelivery: '2026-03-20',
  },
  {
    id: 'D-006',
    storeName: 'Chicago South Loop',
    storeAddress: '1400 S Michigan Ave, Chicago, IL',
    eta: '2026-03-30T10:00',
    driver: 'Mike Johnson',
    status: 'scheduled',
    currentSupplyPct: 52,
    forecastedDepletionDate: '2026-03-31',
    suggestedRestockWindow: 'next_week',
    lastDelivery: '2026-03-20',
  },
];

export const SUPPLY_REQUESTS = [
  {
    id: 'REQ-2026-001',
    store: 'Chicago Downtown',
    ingredientsSummary: 'Cherry syrup, Cola soda',
    submittedDate: '2026-03-27',
    status: 'pending',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-28',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Cherry Syrup', qty: 5, unit: 'cases', aiSuggested: 5 },
      { name: 'Cola Soda', qty: 3, unit: 'cases', aiSuggested: 4 },
    ],
    notes: 'URGENT: Critical shortage of popular items',
    approvalTimeline: [
      { date: '2026-03-27', status: 'submitted', comment: 'Request received' },
    ],
  },
  {
    id: 'REQ-2026-002',
    store: 'Chicago Downtown',
    ingredientsSummary: 'Soda assortment',
    submittedDate: '2026-03-26',
    status: 'approved',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-29',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Cherry Soda', qty: 4, unit: 'cases', aiSuggested: 4 },
      { name: 'Vanilla Soda', qty: 2, unit: 'cases', aiSuggested: 2 },
    ],
    notes: 'Weekly replenishment',
    approvalTimeline: [
      { date: '2026-03-26', status: 'submitted', comment: 'Request received' },
      { date: '2026-03-26', status: 'approved', comment: 'Approved for shipment' },
    ],
  },
  {
    id: 'REQ-2026-003',
    store: 'Chicago North Shore',
    ingredientsSummary: 'Vanilla syrup emergency',
    submittedDate: '2026-03-27',
    status: 'pending',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-28',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Vanilla Syrup', qty: 3, unit: 'cases', aiSuggested: 3 },
    ],
    notes: 'Emergency restock',
    approvalTimeline: [
      { date: '2026-03-27', status: 'submitted', comment: 'Request received' },
    ],
  },
  {
    id: 'REQ-2026-004',
    store: 'Chicago West Loop',
    ingredientsSummary: 'Weekly ingredient request',
    submittedDate: '2026-03-26',
    status: 'in_transit',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-29',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Cherry Syrup', qty: 2, unit: 'cases', aiSuggested: 2 },
      { name: 'Vanilla Soda', qty: 3, unit: 'cases', aiSuggested: 3 },
      { name: 'Caramel Sauce', qty: 2, unit: 'cases', aiSuggested: 2 },
    ],
    notes: 'Regular weekly request',
    approvalTimeline: [
      { date: '2026-03-26', status: 'submitted', comment: 'Request received' },
      { date: '2026-03-26', status: 'approved', comment: 'Approved for shipment' },
      { date: '2026-03-27', status: 'in_transit', comment: 'Shipment on the way' },
    ],
  },
  {
    id: 'REQ-2026-005',
    store: 'Milwaukee Downtown',
    ingredientsSummary: 'Emergency restock',
    submittedDate: '2026-03-27',
    status: 'pending',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-28',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Cherry Syrup', qty: 4, unit: 'cases', aiSuggested: 4 },
      { name: 'Cola Soda', qty: 4, unit: 'cases', aiSuggested: 5 },
    ],
    notes: 'Critical shortage',
    approvalTimeline: [
      { date: '2026-03-27', status: 'submitted', comment: 'Request received' },
    ],
  },
  {
    id: 'REQ-2026-006',
    store: 'Milwaukee Downtown',
    ingredientsSummary: 'Soda restocking',
    submittedDate: '2026-03-27',
    status: 'pending',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-28',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Lime Soda', qty: 3, unit: 'cases', aiSuggested: 3 },
      { name: 'Vanilla Soda', qty: 2, unit: 'cases', aiSuggested: 2 },
    ],
    notes: 'Soda shortage',
    approvalTimeline: [
      { date: '2026-03-27', status: 'submitted', comment: 'Request received' },
    ],
  },
  {
    id: 'REQ-2026-007',
    store: 'Milwaukee Bay View',
    ingredientsSummary: 'Ingredient restocking',
    submittedDate: '2026-03-26',
    status: 'in_transit',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-29',
    completedDate: null,
    ingredientBreakdown: [
      { name: 'Cherry Syrup', qty: 2, unit: 'cases', aiSuggested: 2 },
      { name: 'Mango Soda', qty: 2, unit: 'cases', aiSuggested: 2 },
    ],
    notes: 'Regular weekly request',
    approvalTimeline: [
      { date: '2026-03-26', status: 'submitted', comment: 'Request received' },
      { date: '2026-03-26', status: 'approved', comment: 'Approved for shipment' },
      { date: '2026-03-27', status: 'in_transit', comment: 'Shipment on the way' },
    ],
  },
  {
    id: 'REQ-2026-008',
    store: 'Chicago Lincoln Park',
    ingredientsSummary: 'Weekly assortment',
    submittedDate: '2026-03-25',
    status: 'delivered',
    deliveryType: 'hub',
    sourceStore: null,
    eta: '2026-03-26',
    completedDate: '2026-03-26',
    ingredientBreakdown: [
      { name: 'Cherry Syrup', qty: 2, unit: 'cases', aiSuggested: 2 },
      { name: 'Vanilla Syrup', qty: 2, unit: 'cases', aiSuggested: 2 },
    ],
    notes: 'Regular weekly request',
    approvalTimeline: [
      { date: '2026-03-25', status: 'submitted', comment: 'Request received' },
      { date: '2026-03-25', status: 'approved', comment: 'Approved for shipment' },
      { date: '2026-03-26', status: 'delivered', comment: 'Delivery completed' },
    ],
  },
];

export const RECURRING_SCHEDULES = [
  {
    id: 'RS-001',
    pattern: 'weekly',
    dayOfWeek: 'Monday',
    timeWindowStart: '09:00',
    timeWindowEnd: '12:00',
    hub: 'Chicago Hub',
    stores: ['S-001', 'S-002', 'S-003', 'S-004', 'S-005'],
    nextRunDate: '2026-03-31',
    intervalDays: 7,
  },
  {
    id: 'RS-002',
    pattern: 'weekly',
    dayOfWeek: 'Wednesday',
    timeWindowStart: '14:00',
    timeWindowEnd: '17:00',
    hub: 'Chicago Hub',
    stores: ['S-006', 'S-007', 'S-008'],
    nextRunDate: '2026-04-02',
    intervalDays: 7,
  },
  {
    id: 'RS-003',
    pattern: 'biweekly',
    dayOfWeek: 'Friday',
    timeWindowStart: '10:00',
    timeWindowEnd: '13:00',
    hub: 'Chicago Hub',
    stores: ['S-009', 'S-010'],
    nextRunDate: '2026-04-04',
    intervalDays: 14,
  },
];

export const KPI_DATA = {
  storesAtCritical: 4,
  deliveriesInTransit: 5,
  pendingRequests: 5,
  topTrendingIngredient: 'Cherry Syrup',
  topTrendingPct: 18,
  forecastAccuracyPct: 87,
};

export const HUB_STATUS = {
  name: 'Chicago Hub',
  inventoryPct: 48,
  alertCount: 4,
  activeDeliveries: 5,
  storesNeedingRestock: 4,
  ordersPending: 5,
};

export const ALERTS = [
  {
    id: 'ALERT-001',
    severity: 'critical',
    message: '4 stores at critical supply levels (0-1 days remaining)',
    timestamp: '2026-03-27T08:15',
    dismissed: false,
  },
  {
    id: 'ALERT-002',
    severity: 'warning',
    message: '2 stores at low supply levels (2-3 days remaining)',
    timestamp: '2026-03-27T09:30',
    dismissed: false,
  },
  {
    id: 'ALERT-003',
    severity: 'critical',
    message: 'Cherry Syrup stock critically low across region',
    timestamp: '2026-03-27T10:00',
    dismissed: false,
  },
  {
    id: 'ALERT-004',
    severity: 'warning',
    message: '2 deliveries delayed due to traffic',
    timestamp: '2026-03-27T10:45',
    dismissed: false,
  },
];

export const TOP_TRENDING_DATA = [
  { ingredient: 'Cherry Syrup', thisPeriod: 285, prevPeriod: 245 },
  { ingredient: 'Cola Soda', thisPeriod: 312, prevPeriod: 298 },
  { ingredient: 'Cherry Soda', thisPeriod: 267, prevPeriod: 210 },
  { ingredient: 'Caramel Sauce', thisPeriod: 198, prevPeriod: 182 },
  { ingredient: 'Vanilla Syrup', thisPeriod: 156, prevPeriod: 168 },
];

export const REGIONAL_VARIATION_DATA = [
  { region: 'Chicago', cherry: 245, mango: 180, vanilla: 160, lime: 140 },
  { region: 'Milwaukee', cherry: 212, mango: 155, vanilla: 145, lime: 125 },
  { region: 'Madison', cherry: 185, mango: 165, vanilla: 190, lime: 110 },
  { region: 'Des Moines', cherry: 156, mango: 145, vanilla: 155, lime: 95 },
];

export const SEASONAL_PATTERNS_DATA = [
  { month: 'Jan', cherry: 156, mango: 105, cola: 210 },
  { month: 'Feb', cherry: 168, mango: 120, cola: 225 },
  { month: 'Mar', cherry: 285, mango: 185, cola: 312 },
  { month: 'Apr', cherry: 245, mango: 210, cola: 298 },
  { month: 'May', cherry: 280, mango: 240, cola: 335 },
  { month: 'Jun', cherry: 310, mango: 265, cola: 360 },
];

export const AI_INSIGHTS = [
  'Cherry syrup demand is trending 18% above last period — consider increasing hub stock by 25%',
  'Milwaukee stores show 15% higher cola consumption than other regions',
  'Seasonal pattern suggests 22% increase in demand expected next month',
  'Delivery optimization suggests 3 routes can be consolidated saving ~4 hours weekly',
  'AI forecast accuracy at 87% — sufficient confidence for automated restocking',
];

export const DRIVERS = [
  { id: 'DR-001', name: 'Mike Johnson' },
  { id: 'DR-002', name: 'Sarah Martinez' },
  { id: 'DR-003', name: 'James Rodriguez' },
  { id: 'DR-004', name: 'Robert Chen' },
  { id: 'DR-005', name: 'Lisa Anderson' },
  { id: 'DR-006', name: 'David Thompson' },
  { id: 'DR-007', name: 'Jessica Lee' },
];
